### ISSUE TITLE
plexus-container-default requires a Automatic-Module-Name entry

### ISSUE THREAD

**Issue by cowwoc** [codehaus-plexus/plexus-containers#17] opened 2019-01-23 03:03 UTC
When building a Java9+ project I get the following warning:

`[WARNING] Can't extract module name from plexus-container-default-1.0-alpha-30.jar: plexus.container.default: Invalid module name: 'default' is not a Java identifier`

I believe that JPMS is attempting to convert the JAR into an automatic module but fails to do so for the aforementioned reason.

Please add a `Automatic-Module-Name` entry into MANIFEST.MF to rectify this.

**Comment by cowwoc** [comment] 2019-01-23 03:05
To clarify, here is what I see at build-time:

```
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ code_generator ---
[WARNING] Can't extract module name from plexus-container-default-1.0-alpha-30.jar: plexus.container.default: Invalid module name: 'default' is not a Java identifier
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\Users\Gili\Documents\requirements\code_generator\target\classes
[INFO] 
```

**Comment by sormuras** [comment] 2019-01-23 08:30
Good catch, but it looks like that component is no longer intended to be used. See https://github.com/codehaus-plexus/plexus-containers/commit/1fe972e5b3f2f2cff4cd41a028cada3f1345a01f

**Comment by khmarbaise** [comment] 2019-01-26 18:14
The plexus-container-default should never be used anymore ...So I will close this.

**Closed as completed by khmarbaise** 2019-01-26 18:14 UTC

**Comment by cowwoc** [comment] 2019-01-26 18:25
@sormuras @khmarbaise My project does not depend on `plexus-container-default` directly. How do I find out what is triggering this error? If it's another plugin or annotation processing agent (or similar) I'm not sure how to track the problem to its source.

**Comment by khmarbaise** [comment] 2019-01-27 12:15
@cowwoc Do you have a project link ?

**Comment by cowwoc** [comment] 2019-01-27 14:12
@khmarbaise Typical... I just retried reproducing the issue and it no longer occurs :) I guess we'll leave things as-is until I am able to reproduce this again. Thanks.

**Comment by khmarbaise** [comment] 2019-01-27 14:19
Thanks for the feedback. Yes of course if you can reproduce the issue please file in an issue. Thanks.
